# Generated by Django 4.2.16 on 2024-12-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analisis.categorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoAnalisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "analisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analisis.analisis",
                    ),
                ),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analisis.parametro",
                    ),
                ),
            ],
        ),
    ]
