# Generated by Django 4.2.16 on 2024-12-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("salud", "0001_initial"),
        ("analisis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisis",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salud.paciente"
            ),
        ),
    ]
