version: '3.1'
services:
  cenebell:
    build: .
    env_file:
      - .env
    image: cenebell
    restart: always
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - '.:/app'
    container_name: cenebell
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8051:8000
