# Generated by Django 4.2.16 on 2024-11-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_serial", models.CharField(max_length=50)),
                ("horas_uso", models.IntegerField()),
                ("disponible", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="VisitaMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horas_trabajo", models.IntegerField()),
                ("observaciones", models.TextField()),
                ("fecha_hora", models.DateTimeField()),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maquinas.maquina",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maquinas.tipomantenimiento",
                    ),
                ),
                (
                    "visita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maquinas.visitamantenimiento",
                    ),
                ),
            ],
        ),
    ]
