# Generated by Django 4.2.16 on 2025-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maquinas", "0002_fabricante_tipomaquina_maquina_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maquina",
            old_name="nro_serial",
            new_name="nro_serie",
        ),
    ]
