# Generated by Django 4.2.16 on 2024-12-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maquinas", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("peso_in", models.FloatField()),
                ("peso_out", models.FloatField()),
                ("frecuencia_cardiaca", models.IntegerField()),
                ("presion_a_in", models.IntegerField()),
                ("presion_a_out", models.IntegerField()),
                ("heparina_dosis", models.IntegerField()),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maquinas.maquina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObraSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obra_social",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salud.obrasocial",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_inicio", models.DateTimeField()),
                ("fecha_hora_fin", models.DateTimeField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "dialisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salud.dialisis"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salud.paciente"
                    ),
                ),
                (
                    "persona_responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("descripcion", models.TextField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salud.paciente"
                    ),
                ),
            ],
        ),
    ]
